name: checkout action use
on: workflow_dispatch
jobs: 
  checkout-repo:
    runs-on: ubuuntu-latest
    steps: 
      - name: list files before
        run: ls -a
      - name: print test
        run: echo "hi there"
      
    
