name: github context to Log
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment
        options:
          - test
          - stage
          - prod
      tags:
        description: 'regression or functional'
        required: false
        type: boolean
        
jobs:
  Github_context_to_Log:
    env:
      en: stage
      phase: build      
    runs-on: ubuntu-latest
    steps:    
      - name: dump github context
        env: 
          github_context: ${{ toJson(github) }}
        run: echo "$github_context"
      - name: dump job context to log
        env:
          jobContext: ${{ toJson(job)}}
        run: echo "$jobContext"
      - name: dump env context to log
        env:
          envConext: ${{ toJson(env) }}
        run: echo "$envContext"
      - name: dump matrix context to log
        env: 
          matrixContext: ${{ toJson(matrix) }}
        run: echo "$matrixContext"
      - name: dump steps context to log
        env: 
          stepsContext: ${{ toJson(steps) }}
        run: echo "stepsContext"
      - name: dump runner context to log
        env: 
          runnerContext: ${{ toJson(runner) }}
        run: echo '$runnerContext'
      - name: dump strategy context to log
        env:
          strategyContext: ${{ toJson(strategy) }}
        run: echo "$strategContext"
        


    
    
  
