name: github context to Log
on: workflow_dispatch
jobs:
  Github_context_to_Log:
    runs-on: ubuntu-latest
    steps: 
      - name: dump github context
        env: 
          github_context: ${{ toJson(github) }}
        run: echo "$github_context"
      - name: dump job context to log
        env:
          jobContext: ${{ toJson(job)}}
        run: echo "$jobContext"




    
    
  
