name: git hub actions demo
on: [push]
jobs: 
  MacOS-job:
    runs-on: macos-lastest
    steps: 
    - name: get sw version
      run: sw-vers
  dependent-job:
    runs-on: windows-latest
    needs: MacOS-job
    steps:
      - name: print a string
        run: Write-Output "print string in windows powershell"
      
  Get-java-version:
    runs-on: ubuntu-latest
    steps: 
      - name: get java version
        run: java -version
        
  Run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: single line command
        run: echo "hello world"
      - name: multi line command 
        run: |
          node -v
          npm -v
          
  Explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run : echo "the job was manually triggered by ${{github.event_name}} event."
      - run: echo "the job status is ${{job.status}}."
      - run: echo "the jos is running on ${{runner.os}}."
      - run: echo "the branch is ${{github.ref}}  the repository is ${{github.repository}}."
      - name: checkout Repository
        uses: actions/checkout@v4
      - run: echo "the repository ${{github.repository }} is now clonned at runner machine ${{runner.os}}. "
      - run: echo "the workflow is now ready to test your code on runner"
      - name: list files in the repository
        run: ls ${{github.workspace }}
      - run: echo "the job status is ${{job.status }}."
