name: Java Maven Build with PowerShell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Run PowerShell commands
      shell: pwsh
      run: |
        Write-Host "Java version:"
        java -version

        Write-Host "Maven version:"
        mvn -version

        Write-Host "Running Maven build..."
        mvn clean 

        Write-Output "Fetch Get-History"
        Write-Output Get-History 
        
        Write-Output "(Get-History | Where-Object { $_.CommandLine -like "*mvn*" } )"
        (Get-History | Where-Object { $_.CommandLine -like "*mvn*" } )
        
        Write-Output "(Get-History | Where-Object { $_.CommandLine -like "*mvn*" } | Select-Object -Last 1 -ExpandProperty CommandLine)"
        (Get-History | Where-Object { $_.CommandLine -like "*mvn*" } | Select-Object -Last 1 -ExpandProperty CommandLine) 
        
        Write-Output "(Get-History | Where-Object { $_.CommandLine -like "*mvn*" } | Select-Object -Last 1 -ExpandProperty CommandLine) | New-Item -Path "src/main/resources/getCommand.txt" -ItemType File -Force"
        (Get-History | Where-Object { $_.CommandLine -like "*mvn*" } | Select-Object -Last 1 -ExpandProperty CommandLine) | New-Item -Path "src/main/resources/getCommand.txt" -ItemType File -Force
        

        
