name: test java
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    steps:
      - name: get java version
        run: java -version
      - name: maven version
        run: mvn -version
      - name: checkout repo
        uses: actions/checkout@v4
      - name: compile java
        run: javac Test.java
      - name: execute java file
        run: java Test
        
  




